import chroma from 'chroma-js' 

export const styles =   {
    colorBox : {
        backgroundColor:({color,format})=>color[format],
        width: "100%",
        height: "auto",
        margin: "0 auto",
        position: "relative",
        display: "flex",
        alignItems: "flex-end",
        cursor: "pointer",
        textTransform: "uppercase",
        '&:hover button':{
            opacity:1
        }
    },
    boxContainer : {
        display: "flex",
        width: "100%",
        alignItems: "center",
        justifyContent: "space-between",
    },
    copyButton:{
        color: ({color,format})=>chroma(color[format]).luminance() >= 0.6 ? "rgba(0,0,0,0.6)" : "white",
        width: "100px",
        height: "30px",
        position: "absolute",
        display: "inline-block",
        top:"50%",
        left: "50%",
        marginLeft: "-50px",
        marginTop: "-15px",
        textAlign: "center",
        outline: "none",
        fontSize: "1rem",
        lineHeight: "30px",
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        border: "none",
        opacity: "0",
        textTransform: "uppercase",
        cursor: "pointer",
    },
    seeMore:{
            background:"rgba(255,255,255,.3)",
            color: ({color,format})=>chroma(color[format]).luminance() >= 0.6 ? "rgba(0,0,0,0.6)" : "white",
            borderRadius: "0",
            width: "70px",
            height: "30px",
            lineHeight: "30px",
            textAlign: "center",
            opacity: "1",
            cursor: "pointer",
        
    },
    colorName:{
        color: ({color,format})=>chroma(color[format]).luminance() <= 0.08 ? "white" : "black",
        fontSize: "0.8rem",
        fontWeight: "600",
        marginLeft: "10px",
        letterSpacing: "1px",
    },
    copyText:{
        color: ({color,format})=>chroma(color[format]).luminance() >= 0.6 ? "black" : "white",
        fontSize: "2rem",
        fontWeight: "100",
    },
    copiedText:{
        fontWeight: "400",
        textShadow: "1px 2px black",
        background: "rgba(255,255,255,0.2)",
        width: "100%",
        marginBottom: "0",
        padding: "1rem",
        zIindex:'25'
    },
    copyOverlay:{
        opacity: "0",
        width: "100%",
        height: "100%",
        position: "absolute",
        transform: "scale(0.1)",
        zIndex:'10',
        transition: "transform 0.6s ease-in-out",
        },
    showOverlay:{
        transform: "scale(10)",
        opacity: "1",
        zIindex: "10",
    },
    copyMsg:{
        position: "fixed",
        left: "0",
        right: "0",
        top: "0",
        bottom: "0",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "3rem",
        transform: "scale(0.1)",
        opacity: "0",
        color: "white",
        flexDirection: "column",
        textAlign: "center",
        textTransform: "uppercase",
    },
    showMsg:{
        opacity: "1",
        transform: "scale(1)",
        zIndex: "25",
        transition:"all 0.4s ease-in-out",
        transitionDelay: "0.3s",
    }
    }