export const styles = {
  paletteColors: {
    height: "85vh",
    width: "100vw",
    display: "grid",
    gridTemplateColumns: "repeat(4,1fr)",
    "@media (max-width: 700px)": {
      height: "100%",
      gridTemplateColumns: "repeat(2,1fr)",
    },
    "@media (max-width: 500px)": {
      height: "100%",
      gridTemplateColumns: "repeat(1,1fr)",
    },
  },
  colorBox: {
    backgroundColor: "black",
    width: "100%",

    margin: "0 auto",
    position: "relative",
    display: "flex",
    alignItems: "flex-end",
    cursor: "pointer",
    textTtransform: "uppercase",
    "@media (max-width: 700px)": {
      height: "150px",
    },
    "@media (max-width: 500px)": {},
  },
  backBtn: {
    color: "white",
    width: "100px",
    height: "30px",
    position: "absolute",
    display: "inline-block",
    top: "50%",
    left: "50%",
    marginLeft: "-50px",
    marginTop: "-15px",
    textAlign: "center",
    outline: "none",
    fontSize: "1rem",
    lineHeight: "30px",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    border: "none",
    opacity: "1",
    textTransform: "uppercase",
    cursor: "pointer",
  },
};
