export const SET_LEVEL = "SET_LEVEL";
export const SET_FORMAT = "SET_FORMAT";
export const SET_CURRENT_PALETTE = "SET_CURRENT_PALETTE";
export const CREATE_NEW_PALETTE = "CREATE_NEW_PALETTE";

export const UPDATED_PALETTE = "UPDATED_PALETTE";
